pip install peft
pip install torchvision
pip install OmegaConf
pip install iopath
pip install timm
pip install decord
pip install webdataset
pip install pandas
pip install opencv-python
pip install einops
pip install sentencepiece